### PR TITLE
Improve Haskell highlight queries

### PR DESCRIPTION
**Pull request by farbodsz**
This PR makes improvements to the `highlights.scm` file in 
`tree-sitter-haskell`.

It's partly based off the one by @elianiva from https://github.com/nvim-treesitter/nvim-treesitter/pull/1210.
(I'm aware that PR is still in the works, so wasn't sure whether to open the PR 
here or on the `nvim-treesitter` repo).

Here are the changes I've made compared to the one from the `nvim-treesitter` 
PR:

* Highlight minus sign in negated numbers, e.g. (-10)
* Resolve error when comma captured as punctuation delimiter (previously
  commented out)
* Add semicolon as punctuation delimiter
* Add `case` and `of` to `@conditional` capture group
* Move `qualified` out of `@keyword` and into `@include` capture group
* Add missing operators:
  * `type_operator`
  * Dots from export and record wildcards, i.e. `Record{..}`, `exp (..)`
  * Equals and pipe `=` and `|`
  * Function arrows `=>` and `->`
  * Bind arrow `<-`
  * Lambda operator `\`
  * Treat infix functions as operators (and also highlight the backtick)
  * `@` symbol (except for in the as-pattern, where it is highlighted as
    `@namespace`)
* Highlight namespaces with `@namespace` instead of `@constructor`, e.g.
  in `T.Text`
* Simplify queries for types

There's also a comparison of each of the aforementioned highlights, so you can see the results visually.

_Example 1_

| `tree-sitter-haskell` | `nvim-treesitter` PR | This PR |
| -- | -- | -- |
| screenshot_20210618_213617 | screenshot_20210618_214054 | screenshot_20210618_215022 |

_Example 2_

| `tree-sitter-haskell` | `nvim-treesitter` PR | This PR |
| -- | -- | -- |
| screenshot_20210618_213740 | screenshot_20210618_214235 | screenshot_20210618_215113 |

### CODE REVIEW

**Comment by tek** [comment]
wait, this is rendered by nvim? any clue if there was some recent change that made this possible? I've been having issues like this one https://github.com/tree-sitter/tree-sitter-haskell/issues/35

anyways, looks good!

**Comment by farbodsz** [comment]
Thanks for merging! Yes, it is rendered by nvim.

While I haven't been able to reproduce the exact issue you mentioned, I have noticed Playground not updating at all (for all languages). Not sure if those issues are related but I might look into it further in the near future.

**Comment by theHamsta** [comment]
@elianiva shouldn't `qualified` be also `@include` for us?

**Comment by elianiva** [comment]
> @elianiva shouldn't qualified be also @include for us?

I think it should, but isn't it already the case though?

**Pull request merged**
