### PR TITLE
support all valid unicode chars for varsym

### LINKED ISSUE #93: UnicodeSyntax support
I may be holding it wrong, but at least some unicode symbols are not supported as syntax:

e.g.:

```haskell
processStateUpdater ∷
  ∀ a m.
  (NOMInput a, UpdateMonad m) ⇒
  Config →
  u  a →
  StateT (ProcessState a) m ([NOMError], ByteString)
```

gives me

```
(haskell [0, 0] - [5, 52]
  (top_splice [0, 0] - [5, 52]
    (exp_infix [0, 0] - [5, 52]
      (exp_apply [0, 0] - [1, 9]
        (exp_name [0, 0] - [0, 19]
          (variable [0, 0] - [0, 19]))
        (ERROR [0, 20] - [1, 5]
          (ERROR [0, 20] - [0, 23]))
        (exp_name [1, 6] - [1, 7]
          (variable [1, 6] - [1, 7]))
        (exp_name [1, 8] - [1, 9]
          (variable [1, 8] - [1, 9])))
      (operator [1, 9] - [1, 10])
      (exp_apply [2, 2] - [5, 52]
        (exp_tuple [2, 2] - [2, 29]
          (exp_apply [2, 3] - [2, 13]
            (exp_name [2, 3] - [2, 11]
              (constructor [2, 3] - [2, 11]))
            (exp_name [2, 12] - [2, 13]
              (variable [2, 12] - [2, 13])))
          (comma [2, 13] - [2, 14])
          (exp_apply [2, 15] - [2, 28]
            (exp_name [2, 15] - [2, 26]
              (constructor [2, 15] - [2, 26]))
            (exp_name [2, 27] - [2, 28]
              (variable [2, 27] - [2, 28]))))
        (ERROR [2, 30] - [2, 33]
          (ERROR [2, 30] - [2, 33]))
        (exp_name [3, 2] - [3, 8]
          (constructor [3, 2] - [3, 8]))
        (ERROR [3, 9] - [3, 12]
          (ERROR [3, 9] - [3, 12]))
        (exp_name [4, 2] - [4, 3]
          (variable [4, 2] - [4, 3]))
        (ERROR [4, 4] - [4, 7]
          (ERROR [4, 4] - [4, 7]))
        (exp_name [5, 2] - [5, 8]
          (constructor [5, 2] - [5, 8]))
        (exp_parens [5, 9] - [5, 25]
          (exp_apply [5, 10] - [5, 24]
            (exp_name [5, 10] - [5, 22]
              (constructor [5, 10] - [5, 22]))
            (exp_name [5, 23] - [5, 24]
              (variable [5, 23] - [5, 24]))))
        (exp_name [5, 26] - [5, 27]
          (variable [5, 26] - [5, 27]))
        (exp_tuple [5, 28] - [5, 52]
          (exp_list [5, 29] - [5, 39]
            (exp_name [5, 30] - [5, 38]
              (constructor [5, 30] - [5, 38])))
          (comma [5, 39] - [5, 40])
          (exp_name [5, 41] - [5, 51]
            (constructor [5, 41] - [5, 51])))))))

### PR DESCRIPTION
**Pull request by tek**
Fixes #93.

Not sure what the best place to put this function is. I didn't want to include it in `scanner.c` in order to keep its size manageable. Also unsure whether that header needs to be specified explicitly when building.

@414owen @maxbrunsfeld please advise!

### CODE REVIEW

**Comment by 414owen** [comment]
Good feature.

It's not very usual to put a function definition in a C header file (although quite normal to put functions inside templates inside c++ headers I think...). Would it be possible to make this a C file, mark the function as non-static, and add a predeclaration to the top of scanner.c?

**Comment by tek** [comment]
yeah, that sounds sensible. No idea how to tell tree-sitter about this file though when running `tree-sitter generate`. It doesn't link it on its own at least.
Since we're only using the header in one C file, does it make much of a difference to use a header? I'd assume that an extra C file would have to be specified explicitly in downstream apps like `nvim-treesitter`.

**Comment by tek** [comment]
https://github.com/tree-sitter/tree-sitter/issues/1262

seems we're out of luck

**Comment by tek** [comment]
At least the variant with the header appears to install fine in Neovim!

**Comment by 414owen** [comment]
Okay, well the header sounds like an okay solution :)

Shame we can't have multiple source files though...

**Comment by tek** [comment]
yeah well, if that issue I linked is going to be implemented we can just change it :) so I'll go ahead and merge.

**Pull request merged**
