### PR TITLE
Compile to wasm with patch to web-tree-sitter

### PR DESCRIPTION
**Pull request by wenkokke**
This PR enables compilation of tree-sitter-haskell to wasm, provided that web-tree-sitter has been patched with [this patch](https://github.com/wenkokke/tree-sitter-haskell/blob/tree-sitter-haskell-wasm/tree-sitter.patch).

It does not update the build via node-gyp, and hence does not update binding.gyp to set the correct C++ version, as unfortunately I don't think this would work, given that in emscripten, the honus is on the MAIN_MODULE to export the required standard library functions.

I understand that this PR is far from ideal, but it does provide a temporary fix for #53.

### CODE REVIEW

**Comment by tek** [comment]
this would also be fixed by removing the dependency on c++14, right?

**Comment by maxbrunsfeld** [comment]
Looking at the patch, it seems like the additional symbols are related to C++'s reflection/runtime-type-information features. I'm not sure why those are getting used by the current external scanner; maybe the use of `std::function` involves some type of runtime type reflection? So maybe the current work that @414owen is doing in #54 will help with this problem.

**Comment by wenkokke** [comment]
@tek would you be happy to merge the expansion of parse-examples to web assembly tests?

**Comment by tek** [comment]
sure!

**Pull request closed without merging**
